In [1]:
import numpy as np

## Listas para almacenar pequeñas cantidades de datos unidimensionales

In [14]:
a=[1,3,5,7,9]
print(a)
print(a[2:4]) #imprime las posiciones de la 3 incluyendo la 4
b=[[1,3,5,7,9],[2,4,6,8,10]]
print(b[1][2:4])

[1, 3, 5, 7, 9]
[5, 7]
[6, 8]


In [15]:
a=[1,3,5,7,9]
b=[3,5,6,7,9]
c=a+b #suma los arrays
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


## Para listas

np.array

In [11]:
#as vectors from lists
a=np.array([1,3,5,7,9])
b=np.array([3,5,6,7,9])
c=a+b
print(c)
print(type(c))
c.shape

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


(5,)

## Matrices

In [17]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list
a = np.array (l) # convert a list to an array
print(a)

a.shape
(3, 3)
print(a.dtype ) # get type of an array

# or directly as matrix
M = np.array([[1, 2], [3, 4]])

M.shape


M.dtype

[[1 2 3]
 [3 6 9]
 [2 4 6]]
int32


dtype('int32')

In [22]:
#only one type
#M[0,0] = "hello" #Me da un error de invalidez de no poder poner un array con palabras


M =np.array ([[1, 2], [3, 4]], dtype =complex)
#M=array([[ 1.+0.j, 2.+0.j],[ 3.+0.j, 4.+0.j]])
print(M)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [34]:
print(a)

print(a[0]) # this is just like a list of lists

print(a[1, 2]) # arrays can be given comma separated indices

print(a[1, 1:3]) # and slices

print(a[:,1])

a[1, 2] = 7
print(a)

a[:, 0] = [0, 9, 8]
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]
[0 2 3]
7
[6 7]
[2 6 4]
[[0 2 3]
 [9 6 7]
 [8 4 6]]
[[0 2 3]
 [9 6 7]
 [8 4 6]]


## Generation functions

In [40]:
x = arange(0, 10, 1) # arguments: start, stop, step

np.linspace (0, 10,25)

np.logspace (0, 10, 10, base=numpy.e)


NameError: name 'arange' is not defined

In [42]:
# a diagonal matrix
np.diag ([1,2,3])

b =np.zeros (5)
print(b)

b.dtype

n = 1000
#my_int_array = np.zeros (n, dtype =np.int)

#my_int_array.dtype

c =np.ones ([3,3])


[0. 0. 0. 0. 0.]
