In [1]:
import numpy as np

## Listas para almacenar pequeñas cantidades de datos unidimensionales

In [14]:
a=[1,3,5,7,9]
print(a)
print(a[2:4]) #imprime las posiciones de la 3 incluyendo la 4
b=[[1,3,5,7,9],[2,4,6,8,10]]
print(b[1][2:4])

[1, 3, 5, 7, 9]
[5, 7]
[6, 8]


In [15]:
a=[1,3,5,7,9]
b=[3,5,6,7,9]
c=a+b #suma los arrays
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


## Para listas

np.array

In [11]:
#as vectors from lists
a=np.array([1,3,5,7,9])
b=np.array([3,5,6,7,9])
c=a+b
print(c)
print(type(c))
c.shape

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


(5,)

## Matrices

In [17]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list
a = np.array (l) # convert a list to an array
print(a)

a.shape
(3, 3)
print(a.dtype ) # get type of an array

# or directly as matrix
M = np.array([[1, 2], [3, 4]])

M.shape


M.dtype

[[1 2 3]
 [3 6 9]
 [2 4 6]]
int32


dtype('int32')

In [22]:
#only one type
#M[0,0] = "hello" #Me da un error de invalidez de no poder poner un array con palabras


M =np.array ([[1, 2], [3, 4]], dtype =complex)
#M=array([[ 1.+0.j, 2.+0.j],[ 3.+0.j, 4.+0.j]])
print(M)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [34]:
print(a)

print(a[0]) # this is just like a list of lists

print(a[1, 2]) # arrays can be given comma separated indices

print(a[1, 1:3]) # and slices

print(a[:,1])

a[1, 2] = 7
print(a)

a[:, 0] = [0, 9, 8]
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]
[0 2 3]
7
[6 7]
[2 6 4]
[[0 2 3]
 [9 6 7]
 [8 4 6]]
[[0 2 3]
 [9 6 7]
 [8 4 6]]


## Generation functions

In [62]:
x = np.arange(0, 10, 1) # arguments: start, stop, step

print(np.linspace (0, 10,25))

print(np.logspace (0, 10, 10, base=np.e))


[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]
[1.00000000e+00 3.03773178e+00 9.22781435e+00 2.80316249e+01
 8.51525577e+01 2.58670631e+02 7.85771994e+02 2.38696456e+03
 7.25095809e+03 2.20264658e+04]


In [73]:
# a diagonal matrix
print(np.diag ([1,2,3]))

b =np.zeros (5)
print(b)

b.dtype

n = 1000
my_int_array = np.zeros (n, dtype =int)

my_int_array.dtype

c =np.ones ([3,3])
print(c)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Arreglos creación y uso

In [76]:
d =np.arange (5) # just like range()
print(d)

d[1] = 9.7
print(d) # arrays keep their type even if elements changed

print(d*0.4) # operations create a new array, with new type

d =np.arange (5, dtype=float )
print(d)

np.arange (3, 7, 0.5) # arbitrary start, stop and step


[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]
[0. 1. 2. 3. 4.]


array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [79]:
x, y =np.mgrid [0:5, 0:5] # similar to meshgrid in MATLAB
print(x)

# random data
np.random.rand (5,5)


[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


array([[0.56189003, 0.32763449, 0.59917565, 0.3363028 , 0.06643701],
       [0.70464207, 0.26399841, 0.02597448, 0.77838451, 0.36952389],
       [0.10648136, 0.27586453, 0.76040282, 0.03093001, 0.36212294],
       [0.90974215, 0.51830873, 0.48533899, 0.95539295, 0.52436678],
       [0.92380206, 0.47280913, 0.69903639, 0.97452207, 0.80292231]])

## Creando arreglos

Falta el archivo completo TXT para poder ejecutar las diapositivas 20 y 21

In [ ]:
os.system ('head DeBilt.txt)
"
data =np.genfromtxt ('DeBilt.txt‘, delimiter=',‘, skip_header =

data.shape


In [ ]:
np.savetxt ('datasaved.txt', data)

os.system ('head datasaved.txt')

In [ ]:
M =np.random.rand (3,3)
M

np.save ('saved matrix.npy ',M)

np.load ('saved matrix.npy')


In [58]:
a =np.arange (4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print (c)


arr = np.arange (100, 200)
select = [5, 25, 50, 75,-5]
print(arr [select]) # can use integer lists as indices


arr = np.arange (10, 20).reshape((2,5))


[10.   21.7  25.6  27.55]
[105 125 150 175 195]


## Métodos

In [53]:

arr.sum ()

arr.mean ()

arr.std ()

arr.max ()

arr.min ()


1.2

## Método Sort

In [52]:
arr = np.array ([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

arr.sort () # acts on array itself
print(arr )

x =np.array ([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

print(np.sort (x))

print(x)


[1.2 1.8 2.3 4.5 5.5 6.7]
[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]


## Funciones

In [94]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])
print (a)

a.transpose()

#np.inv(a) esta forma ha sido eliminada en numpy
np.linalg.inv(a)

u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

j = np.array([[0.0,-1.0], [1.0, 0.0]])
np.dot (j, j) # matrix product


[[1. 2.]
 [4. 3.]]


array([[-1.,  0.],
       [ 0., -1.]])

In [84]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])
print(a) 

# Transposición correcta
a_transpuesta = a.T 
print(a_transpuesta)

# Inversa correcta (usando numpy.linalg.inv)
a_inversa = np.linalg.inv(a)
print(a_inversa)

# Matriz identidad
u = np.eye(2)
print(u)

# Matriz de intercambio
j = np.array([[0.0, 1.0], [1.0, 0.0]])

# Producto de matrices
j_cuadrado = np.dot(j, j)
print(j_cuadrado)

[[1. 2.]
 [4. 3.]]
[[1. 4.]
 [2. 3.]]
[[-0.6  0.4]
 [ 0.8 -0.2]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [47]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
suma= a + b
print(suma)
#Se agregan las operaciones guardadas en una variable para guardar todos los resultados
resta= a-b
print(resta)

multiplicación=a * b
print(multiplicación)

división=b / a
print(división)

residuo= a% b
print(residuo)

exponente=b**a
print(exponente)

a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
arraya=a
print(arraya)
arrayb=b
print(arrayb)
array3= a + b
print(array3)


[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [45]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([
1, 3], float)

#Quitar el signo de gato para ver los resultados de cada multiplicacion
a * a

#b * b

#a * b


array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])